import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { M_PLUS_Rounded_1c } from "next/font/google";


// const inter = Inter({ subsets: ["latin"] });
const inter = M_PLUS_Rounded_1c({ weight : '700', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
